# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

install:

  - pip install --upgrade pip
  - pip install tox tox-travis


script:
  - tox


stages:
  - test
  - deploy_pypi



jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/repo_helper_sphinx_theme
        provider: pypi
        user: "DomDF"
        password:
          secure: j70YEpoCNAtT0xTeIxvs21krgPX5zGIXCxjElw3f6zCLVUaZq6GkklsbqA5OiKtne0VOyT7XvFsqbzPHopr9a6CO5skVrxjkmtcEockV16R4ckqsvMCnPQArWu0+5O0iYE0NHU4aGbaPmZ5TMsy4IoM+ozaRe7RARQ1RDT6TCi+ZISI24Rtenvu1v7K5mjdQva579IZ6Un4A5WTq3zT/9oZZM6C9zlkm/b7IdtPRE2fcTsEVM4xGKDnVQ7t51RGcd0Uo5l5S/bidmXogXiluFI6Mpt/qeGFZDwpKrtRYw1KatlQ8wZOt2q5HPZV3v6fDKoHMaJ+QgQtUmFCQWwv97fdUpe2lNLf6h6BHNwRTatZwmkjS/i4tblFkxdL1s94CpSoEAMJUB5LQuSILI7lEqDfTM8Os+JnPVh4XUCiy+W87TQTkt3bvdzlky4aDnGmBxBvCTAY9Ccma95i/qT9AKW4VdBxVbZF3SDxP8jycfTWpDwZ2QosjdnEYKcGSspyRQps5niYP7OMu9Wx7hK+ooZO6b+APBPiiCN3eerv/LOOPG6fx28fM7XbWDQHhkxdC6VXIYa1UaKDzvL2kuQOrBfA+K62rX+/UpUhTbiiISfq7ilRWrVzFkcUJMda5fGevlrAN8jjxqiCjczCllJ3XyeSGcRmEj6NSKN8bXJQ2hj0=
        distributions: "sdist bdist_wheel"
        skip_existing: true
